title: "Alt::BrightonRuby"
email: "andy@goodscary.com"
description: "A slightly odd, quasi-conference for strange times by Andy Croll"
url: "https://alt.brightonruby.com"
twitter_username: andycroll
color: "#343a40"

plugins:
 - jekyll-seo-tag

include:
  - _redirects

exclude:
  - gulpfile.js
  - javascripts/
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - scss/
  - yarn.lock
